### ISSUE TITLE
Constants -> structures&interfaces

### ISSUE THREAD

**Issue by esuwu** [nickeskov/netmon#1]
**Аbstract**
![image](https://user-images.githubusercontent.com/41806871/144986262-90b3de90-1d31-49d5-b69c-2855c25ab89e.png)
Right now all states of the service are described by constants. It would probably be better if they would be structures which would make it possible to store all neccesary data inside the structures. The structures would have one interface in common "MonitorState"

**Comment by esuwu** [comment]
<img width="1043" alt="Снимок экрана 2021-12-07 в 10 38 37" src="https://user-images.githubusercontent.com/41806871/144986636-6adf727b-dd50-4b76-836b-dcd0282baa40.png">
You could also get rid of strings constatns, partially at least

**Comment by nickeskov** [comment]
> <img alt="Снимок экрана 2021-12-07 в 10 38 37" width="1043" src="https://user-images.githubusercontent.com/41806871/144986636-6adf727b-dd50-4b76-836b-dcd0282baa40.png">
> You could also get rid of strings constatns, partially at least

This strings constants are necessary because monitor should process and change state by API call with corresponding state string.

**Comment by nickeskov** [comment]
> **Аbstract** ![image](https://user-images.githubusercontent.com/41806871/144986262-90b3de90-1d31-49d5-b69c-2855c25ab89e.png) Right now all states of the service are described by constants. It would probably be better if they would be structures which would make it possible to store all neccesary data inside the structures. The structures would have one interface in common "MonitorState"


On my mind `NetworkMonitoringState` shouldn't be responsible for any data.
@esuwu , what do you suggest to store in such structure? What kind of date? All necessary data is stored into `statsHistoryDeque`.

**Comment by nickeskov** [comment]
Closing due to age
